# Generated by Django 2.2.3 on 2021-02-15 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210215_1615'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserReview',
        ),
    ]
