# Generated by Django 2.2.3 on 2021-02-17 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210215_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='nmc_num',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
