# Generated by Django 2.2.3 on 2021-02-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210217_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='experience',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
