# Generated by Django 2.2.3 on 2021-02-23 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_doctor_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='experience',
            new_name='experience_yrs',
        ),
    ]
