# Generated by Django 2.2.3 on 2021-02-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='doctor_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=20)),
                ('fee', models.IntegerField()),
                ('identification_image', models.ImageField(upload_to='')),
                ('desc', models.CharField(max_length=100)),
                ('nmc_num', models.CharField(default=' ', max_length=50)),
                ('phone', models.CharField(default=' ', max_length=50)),
                ('qualification', models.CharField(default=' ', max_length=50)),
                ('speciality', models.CharField(default=' ', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Symptoms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sym_name', models.CharField(max_length=30)),
            ],
        ),
    ]
