# Generated by Django 3.1 on 2020-08-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0002_symptoms'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_profile',
            name='nmc_num',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AddField(
            model_name='doctor_profile',
            name='phone',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AddField(
            model_name='doctor_profile',
            name='qualification',
            field=models.CharField(default=' ', max_length=30),
        ),
        migrations.AddField(
            model_name='doctor_profile',
            name='speciality',
            field=models.CharField(default=' ', max_length=30),
        ),
    ]
