# Generated by Django 2.2.3 on 2021-02-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0002_doctor_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('num', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('queries', models.CharField(max_length=200, null=True)),
                ('service', models.CharField(max_length=100)),
            ],
        ),
    ]
