# Generated by Django 3.1 on 2020-08-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0004_auto_20200824_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_profile',
            name='phone',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor_profile',
            name='qualification',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor_profile',
            name='speciality',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
